### ISSUE TITLE
TAP debug

### ISSUE THREAD

**Issue by rdaly525** [leonardt/silica#15]
I wrote up a basic silica coroutine for the TAP fsm, and I am getting a difficult to debug error. This is in the branch tap.

>python tests/test_tap.py
  File "tests/test_tap.py", line 245, in <module>
    test_tap()
  File "tests/test_tap.py", line 204, in test_tap
    si_tap = si.compile(tap, file_name="tests/build/si_tap.v")
  File "/Users/rdaly/silica/silica/compile.py", line 80, in compile
    inline_yield_from_functions(tree, func_globals, func_locals)
  File "/Users/rdaly/silica/silica/transformations/inline_functions.py", line 62, in inline_yield_from_functions
    return YieldFromFunctionInliner(_locals, _globals).visit(tree)
  File "/Users/rdaly/silica/silica/transformations/inline_functions.py", line 21, in visit
    result = self.visit(statement)
  File "/Users/rdaly/silica/silica/transformations/inline_functions.py", line 21, in visit
    result = self.visit(statement)
  File "/Users/rdaly/silica/silica/transformations/inline_functions.py", line 21, in visit
    result = self.visit(statement)
  File "/Users/rdaly/silica/silica/transformations/inline_functions.py", line 28, in visit
    return super().visit(node)
  File "/Users/rdaly/miniconda3/envs/pysilica/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/rdaly/silica/silica/transformations/inline_functions.py", line 36, in visit_Assign
    node.value = self.visit(node.value)
  File "/Users/rdaly/silica/silica/transformations/inline_functions.py", line 20, in visit
    for statement in node.body:
TypeError: 'Num' object is not iterable

Presumably it is complaining about one of my assignments in the coroutine, but I am not sure which one is wrong.

**Comment by hofstee** [comment]
`TMS, TDI = yield #TODO it seems to be failing here`
You probably want to yield a default value here, like bits(0,...) for each output.

**Comment by hofstee** [comment]
`IR = (IR>>1 & ((1<<4)-1)) | (TDI << 3) #TODO how to concat?` in theory you can concat slices using lists in Python but I'm not sure if I implemented that already.

**Comment by rdaly525** [comment]
The yielding a default value (bit(0)) does not seem to help. Also test_fifo.py is an example where not yielding something works fine.

**Comment by leonardt** [comment]
Fixed by 331733f, there was code assuming that if a node has a `body` attribute, it is a list, but that's not a case for the `IfExp` node.

**Comment by leonardt** [comment]
It's now running into a different issue with inferring the type for `NS`

**Comment by leonardt** [comment]
NS type issue fixed by giving it an explicit bit width with fa4dfab, now some other issue in the type checking code

**Comment by hofstee** [comment]
`shift_regA = shift_dr & (IR == 2) #2 is address of regA` is causing the bug

**Comment by leonardt** [comment]
This moves it forward by explicitly promoting the width of TDI before shifting it 4f4103b

**Comment by leonardt** [comment]
More progress by making all the state enums explicitly bits 609a56b

**Comment by leonardt** [comment]
Ok, this gets us through the type checking code, 09c0df8, but now it's hanging later on during liveness analysis, will investigate after lunch

**Comment by hofstee** [comment]
I'm also adding syntax that will let you write `IR = ( TDI, bits(IR >> 1, 3) )`. `[ ... ]` is already used for 2D arrays, but `{ ... }` also seems reasonable here, as it would be the same syntax used for structs and this is basically a struct with anonymous keys, but we're already using tuple syntax `( ... )` for this elsewhere I believe.

Also hangs in liveness.

**Comment by leonardt** [comment]
Passes locally now! Waiting on travis https://github.com/leonardt/silica/compare/tap?expand=1

I made some changes to the test bench to make it work (mainly, renaming TCK to CLK since the silica compiler just assumes the clock will be named CLK).
